WITH ED2 AS (SELECT PARENT_ID, COUNT(*) CHILD_COUNT
FROM ECOLI_DATA GROUP BY PARENT_ID)

SELECT ID, CASE WHEN CHILD_COUNT IS NULL THEN 0 ELSE CHILD_COUNT END CHILD_COUNT
FROM ECOLI_DATA ED1
LEFT JOIN ED2
ON ID=ED2.PARENT_ID
ORDER BY ID