WITH RENT AS ( 
SELECT C.CAR_ID,C.CAR_TYPE,P.DISCOUNT_RATE,C.DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND P.DURATION_TYPE = '30일 이상'
)

SELECT R.CAR_ID, R.CAR_TYPE, ROUND((1-R.DISCOUNT_RATE/100)*R.DAILY_FEE*30) FEE
FROM RENT R
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON R.CAR_ID = H.CAR_ID
AND START_DATE<='2022-11-30' AND END_DATE>='2022-11-01'
WHERE H.CAR_ID IS NULL 
AND ROUND((1-R.DISCOUNT_RATE/100)*R.DAILY_FEE*30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, R.CAR_TYPE, R.CAR_ID DESC