WITH RENT AS (
SELECT C.CAR_TYPE,C.CAR_ID,C.DAILY_FEE,P.DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV')
AND P.DURATION_TYPE = '30일 이상')

SELECT R.CAR_ID, R.CAR_TYPE, ROUND((1-R.DISCOUNT_RATE/100)*30*R.DAILY_FEE) FEE
FROM RENT R
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON R.CAR_ID=H.CAR_ID
AND START_DATE<='2022-11-30' AND END_DATE>='2022-11-01'
WHERE ROUND((1-R.DISCOUNT_RATE/100)*30*R.DAILY_FEE) BETWEEN 500000 AND 1999999
AND H.CAR_ID IS NULL
ORDER BY FEE DESC, R.CAR_TYPE,R.CAR_ID DESC