with dis_fee as (
SELECT C.CAR_ID,C.CAR_TYPE,C.DAILY_FEE,P.DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV') AND P.DURATION_TYPE = '30일 이상'
)

SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE * 30 *(1-c.DISCOUNT_RATE/100),0) FEE
FROM dis_fee c
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON c.CAR_ID=H.CAR_ID
AND H.START_DATE<='2022-11-30' AND H.END_DATE>='2022-11-01'
WHERE h.CAR_ID IS NULL AND ROUND(c.DAILY_FEE * 30 *(1-c.DISCOUNT_RATE/100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC