WITH A AS (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) PER
           FROM ECOLI_DATA)
           

SELECT ID, CASE WHEN A.PER<=0.25 THEN "CRITICAL"
WHEN A.PER<=0.5 THEN 'HIGH'
WHEN A.PER<=0.75 THEN 'MEDIUM'
WHEN A.PER>0.75 THEN 'LOW' ELSE '1' END COLONY_NAME
FROM A
ORDER BY A.ID