SELECT YEAR(S.SALES_DATE) YEAR,MONTH(S.SALES_DATE) MONTH,COUNT(DISTINCT(I.USER_ID)) PURCHASED_USERS, ROUND(COUNT(DISTINCT(I.USER_ID))/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)='2021'),1) PUCHASED_RATIO
FROM USER_INFO I
INNER JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
WHERE YEAR(I.JOINED)='2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH