WITH RENT AS (
SELECT H.HISTORY_ID, DATEDIFF(END_DATE,START_DATE)+1 days,C.DAILY_FEE, c.car_type,
    CASE WHEN DATEDIFF(END_DATE,START_DATE)+1>=90 THEN '90일 이상'
    WHEN DATEDIFF(END_DATE,START_DATE)+1>=30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE,START_DATE)+1>=7 THEN '7일 이상'
    ELSE '7일 미만' END duration_type
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE='트럭')

SELECT R.HISTORY_ID HISTORY_ID, ROUND((1-IFNULL(P.DISCOUNT_RATE,0)/100)*r.days*r.daily_fee) FEE
FROM RENT R
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.duration_type= r.duration_type
and p.car_type=r.car_type
ORDER BY FEE DESC, HISTORY_ID DESC