WITH RENT AS (SELECT C.DAILY_FEE, C.CAR_TYPE,H.HISTORY_ID,
              DATEDIFF(END_DATE,START_DATE)+1 DAYS,
              CASE WHEN DATEDIFF(END_DATE,START_DATE)>=90 THEN '90일 이상'
              WHEN DATEDIFF(END_DATE,START_DATE)>=30 THEN '30일 이상'
              WHEN DATEDIFF(END_DATE,START_DATE)>=7 THEN '7일 이상'
              ELSE '7일 미만' END DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE='트럭')

SELECT R.HISTORY_ID, ROUND((1-IFNULL(P.DISCOUNT_RATE,0)/100)*R.DAYS*R.DAILY_FEE) FEE
FROM RENT R
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON R.CAR_TYPE=P.CAR_TYPE
AND R.DURATION_TYPE=P.DURATION_TYPE
ORDER BY FEE DESC, R.HISTORY_ID DESC