WITH RECURSIVE TIME AS (
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR +1
FROM TIME
WHERE HOUR < 23
)

SELECT T.HOUR HOUR,COUNT(ANIMAL_ID)
FROM TIME T
LEFT JOIN ANIMAL_OUTS O
ON T.HOUR=HOUR(DATETIME)
GROUP BY T.HOUR
ORDER BY HOUR
