WITH RENT AS (
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY H.CAR_ID
HAVING COUNT(*) >=5)

SELECT MONTH(START_DATE) MONTH, R.CAR_ID, COUNT(*) RECORDS
FROM RENT R
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON R.CAR_ID = H.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, R.CAR_ID
ORDER BY MONTH, R.CAR_ID DESC