SELECT D.ID,D.EMAIL,D.FIRST_NAME,D.LAST_NAME
FROM DEVELOPERS D
WHERE SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME='C#')>0
OR SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME='Python')>0
ORDER BY D.ID