-- 코드를 입력하세요
SELECT TITLE, B.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE,'YYYY-MM-DD') CREATED_DATE
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_REPLY R
ON B.BOARD_ID=R.BOARD_ID
WHERE TO_CHAR(B.CREATED_DATE,'YYYY-MM') LIKE '%2022-10'
ORDER BY R.CREATED_DATE, TITLE